- hosts: client1
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    yum:
        pkg: httpd
        state: latest
  - name: write the apache config file
    tasks:
    shell: 'echo "Hi, This is Arulraj Anto, test page 1" > /var/www/html/index.html'

  - name: restart apache
    service:
        name: httpd
        state: started
        enabled: yes
